name: ubuntu-minimal_usage
on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
# Declare default permissions as read only.
permissions: read-all
jobs:
  minimal_usage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: eessi/github-action-eessi@v3
    - name: Test EESSI
      run: |
        module load EESSI-extend
        eb --software-commit=$GITHUB_SHA easybuild/BCFtools-devel-GCC-13.2.0.eb
      shell: bash
